/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.30.9-11-geedf76f8e (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.30.9-11-geedf76f8e"
#endif
#define SDL_REVISION_NUMBER 0
